### PR TITLE
[TIMOB-25320] Fix bug when xcode eula is not accepted

### PR DESCRIPTION
**Pull request by ewanharris**
JIRA: https://jira.appcelerator.org/browse/TIMOB-25320

Do not attempt to run simctl if we have a selectedXcode but the EULA is not accepted

### CODE REVIEW

**Comment by hansemannn** [comment]
Didn't we catch that at an earlier stage back in the days? I remember we've thrown an "Please accept and retry" error log. Maybe we can guard it in there as well.

**Comment by ewanharris** [comment]
@hansemannn It still logs that

ti info -t ios
```
Titanium Command-Line Interface, CLI version 5.0.14, Titanium SDK version 6.2.0.GA
Copyright (c) 2012-2017, Appcelerator, Inc.  All Rights Reserved.

Please report bugs to http://jira.appcelerator.org/

Xcode
  9.0 (build 9A235) - Xcode default
    Install Location          = /Applications/Xcode.app/Contents/Developer
    iOS SDKs                  = 11.0
    iOS Simulators            = 11.0
    Watch SDKs                = 4.0
    Watch Simulators          = 4.0
    Supported by TiSDK 6.2.0.GA = yes
    EULA Accepted             = no
    Teams                     = none
 
iOS Keychains
  login.keychain-db           = /Users/awam/Library/Keychains/login.keychain-db
  System.keychain             = /Library/Keychains/System.keychain

iOS Development Certificates
  None

iOS App Store Distribution Certificates
  None

Apple WWDR Certificate
  Apple WWDR                  = installed

Development iOS Provisioning Profiles
  None

App Store Distribution iOS Provisioning Profiles
  None

Ad Hoc iOS Provisioning Profiles
  None

Enterprise Ad Hoc iOS Provisioning Profiles
  None

iOS Simulators
  None

WatchOS Simulators
  None

Connected iOS Devices
  None

iOS Issues
  !  Unable to find any valid iOS development provisioning profiles.
     This will prevent you from building apps for testing on iOS devices.
     You will need to log in to http://appcelerator.com/ios-dev-certs with your Apple Developer
     account, then create, download, and install a profile.

  !  Unable to find any valid iOS adhoc provisioning profiles.
     This will prevent you from packaging apps for adhoc distribution.
     You will need to log in to http://appcelerator.com/ios-dist-certs with your Apple Developer
     account, then create, download, and install a profile.

  !  Unable to find any valid iOS distribution provisioning profiles.
     This will prevent you from packaging apps for AppStore distribution.
     You will need to log in to http://appcelerator.com/ios-dist-certs with your Apple Developer
     account, then create, download, and install a profile.

  !  Unable to find any valid iOS developer certificates.
     This will prevent you from building apps for iOS devices.
     You will need to log in to http://appcelerator.com/ios-dev-certs with your Apple Developer
     account, then create, download, and install a certificate.

  !  Unable to find any valid iOS production distribution certificates.
     This will prevent you from packaging apps for distribution.
     You will need to log in to http://appcelerator.com/ios-dist-certs with your Apple Developer
     account, then create, download, and install a certificate.

  ✕  Xcode EULA has not been accepted.
     Launch Xcode and accept the license.


```

ti build -p ios
```
Titanium Command-Line Interface, CLI version 5.0.14, Titanium SDK version 6.2.0.GA
Copyright (c) 2012-2017, Appcelerator, Inc.  All Rights Reserved.

Please report bugs to http://jira.appcelerator.org/

[WARN]  Support for Node.js v8.5.0 has not been verified for Titanium SDK 6.2.0.GA
[WARN]  If you run into issues, try downgrading to Node.js v6

[ERROR] Xcode EULA has not been accepted.

[ERROR] Launch Xcode and accept the license.
```

**Comment by hansemannn** [comment]
Ok then! Btw, we removed watchOS 1 support a while ago, we should remember to remove the logic from here soon.

**Comment by cb1kenobi** [comment]
PR **APPROVED**

**Comment by cb1kenobi** [comment]
@hansemannn Titanium removed support for watchOS 1, that doesn't mean that ioslib should. We should leave the watchOS 1 detection code alone for the foreseeable future.

**Comment by hansemannn** [comment]
Good reason!

**Pull request merged**
